code --install-extension GitHub.github-vscode-theme
code --install-extension esbenp.prettier-vscode
code --install-extension bmalehorn.shell-syntax
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension redhat.ansible
code --install-extension redhat.vscode-yaml
code --install-extension redhat.java
code --install-extension jeff-hykin.better-dockerfile-syntax
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag 
code --install-extension yzhang.markdown-all-in-one
code --install-extension dbaeumer.vscode-eslint
code --install-extension VisualStudioExptTeam.vscodeintellicode
